
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("JOSE","RODRIGUEZ","Masculino",69412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("PEPE","AGGG","PEP2E@PEPE.ES",68941231);
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("JUAN","RONALDINHO","Masculino",68412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("PEDRO","ROBINHO","Masculino",69412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("MARIA","KAKA","Femenino",68415341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("JULIA","PELE","Femenino",68918341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("DRI","RONALDO","Masculino",61912341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("DARIO","ROMARIO","Masculino",69412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("DANIEL","RUIZ","Masculino",64412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO,sexo,TELEFONO) VALUES("JOSE2","GUER","Masculino",67022341);



