
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("JOSE","RODRIGUEZ","Masculino",69412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("PEPE","AGGG","masculino",68941231);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("JUAN","RONALDINHO","Masculino",68412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("PEDRO","ROBINHO","Masculino",69412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("MARIA","KAKA","Femenino",68415341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("JULIA","PELE","Femenino",68918341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("DRI","RONALDO","Masculino",61912341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("DARIO","ROMARIO","Masculino",69412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("DANIEL","RUIZ","Masculino",64412341);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, sexo, TELEFONO) VALUES("JOSE2","GUER","Masculino",67022341);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, p_unitario, EXISTENCIAS) VALUES("Manzana","Fruta roja", 2.05, 100);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, p_unitario, EXISTENCIAS) VALUES("Almendras","Fruto seco", 5.55, 25);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, p_unitario, EXISTENCIAS) VALUES("Solomillo","Carne de ternera", 10.99, 10);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, p_unitario, EXISTENCIAS) VALUES("Yogures","Yogur griego de Danone", 1.80, 2000);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, p_unitario, EXISTENCIAS) VALUES("Limon","Fruta roja", 2.05, 100);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, p_unitario, EXISTENCIAS) VALUES("Melocoton","Fruto seco", 5.55, 25);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, p_unitario, EXISTENCIAS) VALUES("Huevos","Carne de ternera", 10.99, 10);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, p_unitario, EXISTENCIAS) VALUES("Perones","Yogur griego de Danone", 1.80, 2000);


INSERT INTO VENTAS (n_cliente, CLAVE, CANTIDAD, SUBTOTAL, IVA, TOTAL) VALUES(1, 2, 1, 5.55, 5.55, 1.23);
INSERT INTO VENTAS (n_cliente, CLAVE, CANTIDAD, SUBTOTAL, IVA, TOTAL) VALUES(2, 3, 1, 10.99, 10.99, 1.23);